name: TP Agiles Ahorcado
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: [windows-latest]    
    name: Dotnet build
    steps:
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.0.3
        
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
  
      - name: Run Tests
        working-directory: ./src
        run: msbuild test
