name: TP Agiles Ahorcado
on:
  push:
    branches: 
      - master
env:
  AZURE_WEBAPP_NAME: ma-ahorcado
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NUGET_VERSION: '4.8.x'

jobs:
  build-and-test:
    runs-on: [windows-latest]    
    name: Dotnet build
    steps:
        # Build Solution
      - name: checkout
        uses: actions/checkout@v2.3.4
        
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1.0.3
        
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.5
  
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Restore nuget packages
        run: |
          nuget restore .\AgilesGrupoCondor.sln

      - name: Build Solution
        run: |
          msbuild.exe .\AgilesGrupoCondor.sln /p:platform="Any CPU" /p:configuration="Release" /p:OutputPath=.\build
          
          
        # Unit Testing
      - name: Run Tests
        run: vstest.console.exe .\TPAgilesGrupo1\build\TPAgilesGrupo1.dll
      
      
        # SonarQube
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"OscarDorronzoro_TPAgilesGrupo1" /o:"oscardorronzoro-1" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
          nuget restore .\TPAgilesGrupo1.sln
          msbuild.exe .\TPAgilesGrupo1\TPAgilesGrupo1.csproj /t:Rebuild #build command
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
  
  
#        # Deployment to Azure
#      - name: Deploy to Azure
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: ${{env.AZURE_WEBAPP_NAME}}
#          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
#          package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/TPAgilesGrupo1
      
  build-and-deploy:
    runs-on: windows-latest
    
    steps:

    - uses: actions/checkout@main  
    
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{env.NUGET_VERSION}}
    - name: NuGet to restore dependencies as well as project-specific tools that are specified in the project file
      run: nuget restore
  
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Run MSBuild
      run: msbuild .\TestAzure\TestAzure.vbproj
       
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/TPAgilesGrupo1/'
      
      
      
      
    
    
    
