name: TP Agiles Ahorcado
on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest    
    name: Dotnet build
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0'
      - run: dotnet build TPAgilesGrupo1.sln
